project_name: subshells
before:
  hooks:
    - go mod tidy
builds:
  - id: "subshells"
    main: ./cmd/subshells
    binary: subshells
    goos:
      - linux
      - darwin
    flags:
      - -trimpath
      - -v
    ldflags:
      - main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`
  - id: "infiniteloop"
    main: ./cmd/infiniteloop
    binary: "infiniteloop"
    goos:
      - linux
      - darwin
    flags:
      - -trimpath
      - -v
    ldflags:
      - main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-{{ .ShortCommit }}"
release:
  prerelease: auto
  # Defaults to empty.
  footer: |
    ## Docker images

    `docker pull ghcr.io/kakkoyun/subshells:{{ .Tag }}`
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
