---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: subshells
    app.kubernetes.io/name: subshells
    app.kubernetes.io/version: v0.3.0
  name: subshells
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: workload
      app.kubernetes.io/instance: subshells
      app.kubernetes.io/name: subshells
  template:
    metadata:
      labels:
        app.kubernetes.io/component: workload
        app.kubernetes.io/instance: subshells
        app.kubernetes.io/name: subshells
        app.kubernetes.io/version: v0.3.0
    spec:
      containers:
      - name: subshells
        ports:
        - containerPort: 8080
          name: http
        args:
          - /bin/subshells
          - --address=:8080
          - --log-level=info
        image: ghcr.io/kakkoyun/subshells:v0.3.0
        livenessProbe:
          httpGet:
            host: localhost
            path: /live
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            host: localhost
            path: /ready
            port: 8080
          initialDelaySeconds: 10
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: subshells
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: subshells
    app.kubernetes.io/name: subshells
  name: default
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: subshells
    app.kubernetes.io/name: subshells
