name: goreleaser

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

     - name: Set up Go
       uses: actions/setup-go@v3
       with:
          go-version-file: .go-version
          check-latest: true
          cache: true

     # TODO(kakkoyun): Disabled until fixing the authentication issue.
     #      - name: Login to Github Container Registry
     #        uses: docker/login-action@v1
     #        with:
     #          registry: ghcr.io
     #          username: ${{ github.actor }}
     #          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # GITHUB_TOKEN

     - name: Run GoReleaser
       uses: goreleaser/goreleaser-action@v2
       if: startsWith(github.ref, 'refs/tags/')
       with:
         distribution: goreleaser
         version: latest
         args: release --rm-dist
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container:
    name: Container build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build container
        run: make container

      - name: Login to registry
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login -u kakkoyun --password-stdin ghcr.io

      - name: Push container
        run: |
          make push-container
